### ISSUE TITLE
fastDeploy.py --h should not work.

### ISSUE THREAD

**Issue by preetham** [notAI-tech/fastDeploy#23]
Steps to replicate:
- Download the latest `fastDeploy.py` cli from repo.
- Execute `fastDeploy.py --l` 

This shouldn't work as the shortcut is supposed to be `fastDeploy.py -l` (which also works) and the long form trigger is `fastDeploy.py --list_recipes`.

**Comment by bedapudi6788** [comment]
Added a new label for CLI bugs, since they are not as important as fastDeploy core bugs.
